### ISSUE TITLE
How to withdraw funds when goal is reached ?

### ISSUE THREAD

**Issue by hassan4702** [BahadorGh/Donation-Dapp#10]
when the ETH goal is reached how can the campaign creator withdraw the donated ETH.
Please respond ASAP

**Comment by BahadorGh** [comment]
> when the ETH goal is reached how can the campaign creator withdraw the donated ETH.
> 
> Please respond ASAP

Hey,
As it was a long time ago, I really don't remember well, but definitely he can withdraw the donated amount via explorer.

Also I think it might be visible as a button in the my-campaigns section.

**Comment by hassan4702** [comment]
Hi @BahadorGh ,
It took me some time but I finally figured it out :)
Thank you

**Comment by hassan4702** [comment]
Hi @BahadorGh ,
It took me some time but I finally figured it out :)
Thank you
