### ISSUE TITLE
How to delete Campaign?

### ISSUE THREAD

**Issue by connectsalman** [BahadorGh/Donation-Dapp#2]
My campaign has been duplicated, can I delete one of the duplicated campaign?

**Comment by ace9786** [comment]
how did you deploy this project after cloning?
i am stuck after clicking on submit button loader came and no active data came but it is updated on third web.
do you have any idea

**Comment by BahadorGh** [comment]
@connectsalman yes you can delete the campaign.
If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons.
After clicking on **Delete** button, you can delete your campaign.

**Comment by Manisha6060** [comment]
> @connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons. After clicking on **Delete** button, you can delete your campaign.

After deleting a campaign something like this happening.
![Screenshot (67)](https://github.com/BahadorGh/Donation-Dapp/assets/140041638/e9a71c63-8321-4377-a537-a7fb6b85c3bc)

**Comment by Manisha6060** [comment]
> @connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons. After clicking on **Delete** button, you can delete your campaign.

Also when the campaign reaches to the deadline it did not get deleted automatically.

**Comment by bghad1** [comment]
> > @connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons. After clicking on **Delete** button, you can delete your campaign.
> 
> Also when the campaign reaches to the deadline it did not get deleted automatically.

I have to check it. Maybe it is not implemented for the deadline

**Comment by BahadorGh** [comment]
@connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are Edit and Delete buttons. After clicking on Delete button, you can delete your campaign.

Also when the campaign reaches to the deadline it did not get deleted automatically.

I have to check it. Maybe it is not implemented for the deadline

**Comment by BahadorGh** [comment]
> > @connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons. After clicking on **Delete** button, you can delete your campaign.
> 
> Also when the campaign reaches to the deadline it did not get deleted automatically.

I have to check it. Maybe it is not implemented for the deadline

**Comment by Manisha6060** [comment]
> > > @connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons. After clicking on **Delete** button, you can delete your campaign.
> > 
> > 
> > Also when the campaign reaches to the deadline it did not get deleted automatically.
> 
> I have to check it. Maybe it is not implemented for the deadline

Hey you got the solution?

**Comment by connectsalman** [comment]
> how did you deploy this project after cloning? i am stuck after clicking on submit button loader came and no active data came but it is updated on third web. do you have any idea

**Comment by connectsalman** [comment]
> > > @connectsalman yes you can delete the campaign. If you work with my repo, after going to your campaign(the campaign, which your wallet is the creator of that), there are **Edit** and **Delete** buttons. After clicking on **Delete** button, you can delete your campaign.
> > 
> > 
> > Also when the campaign reaches to the deadline it did not get deleted automatically.
> 
> I have to check it. Maybe it is not implemented for the deadline

Kindly guide me which file contains the delete and edit option?
