### ISSUE TITLE
how to implement the campaigntypes.sol file?

### ISSUE THREAD

**Issue by thunder1911** [BahadorGh/Donation-Dapp#5]
Have you updated the campaigntypes.sol file?

**Comment by BahadorGh** [comment]
Hey @thunder1911 
No, it is not implemented yet.

**Comment by thunder1911** [comment]
> Hey @thunder1911 No, it is not implemented yet.

are u going to implement it?

**Comment by BahadorGh** [comment]
> > Hey @thunder1911 No, it is not implemented yet.
> 
> are u going to implement it?

I hope so. Due to the lack of time, it's kinda hard to say right now, but trying my best for that.

**Comment by thunder1911** [comment]
ohk fine it would be good if u implement it.
