### ISSUE TITLE
how to solve this error while deploying the contract on localhost?

### ISSUE THREAD

**Issue by thunder1911** [BahadorGh/Donation-Dapp#7]
![Screenshot 2024-03-17 203923](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/b5e61b8d-2c1f-4d40-8ff6-1daacf8d38f1)

**Comment by BahadorGh** [comment]
> ![Screenshot 2024-03-17 203923](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/b5e61b8d-2c1f-4d40-8ff6-1daacf8d38f1)
> 
> 

The verification of contract is not available on local host. You can use other chains, or comment the wait for specific block part.

**Comment by thunder1911** [comment]
so what should i do now?can u please help me with i want to complete this project any how


> > ![Screenshot 2024-03-17 203923](https://private-user-images.githubusercontent.com/116245115/313501897-b5e61b8d-2c1f-4d40-8ff6-1daacf8d38f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTU4NjUsIm5iZiI6MTcxMDc5NTU2NSwicGF0aCI6Ii8xMTYyNDUxMTUvMzEzNTAxODk3LWI1ZTYxYjhkLTJjMWYtNGQ0MC04ZmY2LTFkYWFjZjhkMzhmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQyMDU5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDM3ZDFlZDQ0ZGVkMGE3MGJmZmQ0OGJjNDE5MWY1ZDhkNDJiNTkwMTVkY2UwZWMyOWMzZTRiNjhmOGJmNjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y76TToGqcZAyKxDme4k5I1dSqZEXV8hCsFKcW_UDqjE)
> 
> The verification of contract is not available on local host. You can use other chains, or comment the wait for specific block part.

**Comment by thunder1911** [comment]
i did commented the wait for blocks in deploy.js while deploying on local host. what should i do now?is there any issue in etherscan or metamask?

**Comment by BahadorGh** [comment]
> i did commented the wait for blocks in deploy.js while deploying on local host. what should i do now?
> 
> 

Just comment these two lines in the deploy.js file:

```

await waitForTargetBlock(confirmationsNnumber);
  verifyContract(Contract, platformTax);

```
And now you are good to go

**Comment by thunder1911** [comment]
> > i did commented the wait for blocks in deploy.js while deploying on local host. what should i do now?
> 
> Just comment these two lines in the deploy.js file:
> 
> ```
> 
> await waitForTargetBlock(confirmationsNnumber);
>   verifyContract(Contract, platformTax);
> ```
> 
> And now you are good to go

![Screenshot 2024-03-19 025808](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/9a119da1-67f3-4c67-b353-d5f48846e73d)

it says it got deployed to local host then what should i do?

**Comment by BahadorGh** [comment]
> > > i did commented the wait for blocks in deploy.js while deploying on local host. what should i do now?
> 
> > 
> 
> > Just comment these two lines in the deploy.js file:
> 
> > 
> 
> > ```
> 
> > 
> 
> > await waitForTargetBlock(confirmationsNnumber);
> 
> >   verifyContract(Contract, platformTax);
> 
> > ```
> 
> > 
> 
> > And now you are good to go
> 
> 
> 
> ![Screenshot 2024-03-19 025808](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/9a119da1-67f3-4c67-b353-d5f48846e73d)
> 
> 
> 
> it says it got deployed to local host then what should i do?
> 
> 

So everything is settled up.
Now follow the instructions at the root of the project.

**Comment by thunder1911** [comment]
![Screenshot 2024-03-19 030232](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/2675fefa-b938-478c-96b2-419e7474e604)
its showing this

**Comment by thunder1911** [comment]
> > > > i did commented the wait for blocks in deploy.js while deploying on local host. what should i do now?
> > 
> > 
> > > 
> > 
> > 
> > > Just comment these two lines in the deploy.js file:
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > await waitForTargetBlock(confirmationsNnumber);
> > 
> > 
> > > verifyContract(Contract, platformTax);
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > And now you are good to go
> > 
> > 
> > ![Screenshot 2024-03-19 025808](https://private-user-images.githubusercontent.com/116245115/313841094-9a119da1-67f3-4c67-b353-d5f48846e73d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTc4NzcsIm5iZiI6MTcxMDc5NzU3NywicGF0aCI6Ii8xMTYyNDUxMTUvMzEzODQxMDk0LTlhMTE5ZGExLTY3ZjMtNGM2Ny1iMzUzLWQ1ZjQ4ODQ2ZTczZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQyMTMyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzViN2FmOTg1ODk5OTU2MjAyZGI1MGFhZjZkYzQ3MDIxODNhNDlmNDdiMWFhY2IwNDVkNjMyZmMxOTcwNmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QV2CL7PMqI3ybWUCpVjQt7ut16zEMGk_IxVQKICnNH0)
> > it says it got deployed to local host then what should i do?
> 
> So everything is settled up. Now follow the instructions at the root of the project.

where are the next instruction after deploying on local host?

**Comment by BahadorGh** [comment]
> > > > > i did commented the wait for blocks in deploy.js while deploying on local host. what should i do now?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Just comment these two lines in the deploy.js file:
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > await waitForTargetBlock(confirmationsNnumber);
> 
> > > 
> 
> > > 
> 
> > > > verifyContract(Contract, platformTax);
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > And now you are good to go
> 
> > > 
> 
> > > 
> 
> > > ![Screenshot 2024-03-19 025808](https://private-user-images.githubusercontent.com/116245115/313841094-9a119da1-67f3-4c67-b353-d5f48846e73d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTc4NzcsIm5iZiI6MTcxMDc5NzU3NywicGF0aCI6Ii8xMTYyNDUxMTUvMzEzODQxMDk0LTlhMTE5ZGExLTY3ZjMtNGM2Ny1iMzUzLWQ1ZjQ4ODQ2ZTczZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQyMTMyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzViN2FmOTg1ODk5OTU2MjAyZGI1MGFhZjZkYzQ3MDIxODNhNDlmNDdiMWFhY2IwNDVkNjMyZmMxOTcwNmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QV2CL7PMqI3ybWUCpVjQt7ut16zEMGk_IxVQKICnNH0)
> 
> > > it says it got deployed to local host then what should i do?
> 
> > 
> 
> > So everything is settled up. Now follow the instructions at the root of the project.
> 
> 
> 
> where are the next instruction after deploying on local host?

Did you followed instructions in the web3 folder too?

**Comment by thunder1911** [comment]
![Screenshot 2024-03-19 031532](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/abc9a477-caa2-46ee-9e7a-51b710971cb2)
sir i created a campaign but its not showing in my dashboard.? how should i solve this error as i can submit a campaign but its not displaying.

**Comment by thunder1911** [comment]
do i have to uncomment the above commented lines?

**Comment by BahadorGh** [comment]
> ![Screenshot 2024-03-19 031532](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/abc9a477-caa2-46ee-9e7a-51b710971cb2)
> 
> sir i created a campaign but its not showing in my dashboard.? how should i solve this error as i can submit a campaign but its not displaying.

Check if your deployed contract address is equal to what has been saved in the client/src/abi/contract-address.json

**Comment by thunder1911** [comment]
> > ![Screenshot 2024-03-19 031532](https://private-user-images.githubusercontent.com/116245115/313845004-abc9a477-caa2-46ee-9e7a-51b710971cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Nzg2NDUsIm5iZiI6MTcxMDg3ODM0NSwicGF0aCI6Ii8xMTYyNDUxMTUvMzEzODQ1MDA0LWFiYzlhNDc3LWNhYTItNDZlZS05ZTdhLTUxYjcxMDk3MWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxOTU5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGMwZmUwMTU2ZDEzMzZiYzcwMWNiZGJmMDJjYTU5YzM5M2E2ZWY1OWIxNWE0NWVlNDA0ZDEzNzgyZjZjZTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnHDv7mEa0Iq4faYWjY3POTTzrBnJab66OQk9MAoiek)
> > sir i created a campaign but its not showing in my dashboard.? how should i solve this error as i can submit a campaign but its not displaying.
> 
> Check if your deployed contract address is equal to what has been saved in the client/src/abi/contract-address.json

yaa its the same as i uploaded on localhost
sir actually i need your help in this as i have to execute this project in urgent

**Comment by thunder1911** [comment]
> > > ![Screenshot 2024-03-19 031532](https://private-user-images.githubusercontent.com/116245115/313845004-abc9a477-caa2-46ee-9e7a-51b710971cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Nzg2NDUsIm5iZiI6MTcxMDg3ODM0NSwicGF0aCI6Ii8xMTYyNDUxMTUvMzEzODQ1MDA0LWFiYzlhNDc3LWNhYTItNDZlZS05ZTdhLTUxYjcxMDk3MWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxOTU5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGMwZmUwMTU2ZDEzMzZiYzcwMWNiZGJmMDJjYTU5YzM5M2E2ZWY1OWIxNWE0NWVlNDA0ZDEzNzgyZjZjZTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnHDv7mEa0Iq4faYWjY3POTTzrBnJab66OQk9MAoiek)
> > > sir i created a campaign but its not showing in my dashboard.? how should i solve this error as i can submit a campaign but its not displaying.
> > 
> > 
> > Check if your deployed contract address is equal to what has been saved in the client/src/abi/contract-address.json
> 
> yaa its the same as i uploaded on localhost sir actually i need your help in this as i have to execute this project in urgent

should i change it to sepolia contract address??

**Comment by BahadorGh** [comment]
> > > ![Screenshot 2024-03-19 031532](https://private-user-images.githubusercontent.com/116245115/313845004-abc9a477-caa2-46ee-9e7a-51b710971cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Nzg2NDUsIm5iZiI6MTcxMDg3ODM0NSwicGF0aCI6Ii8xMTYyNDUxMTUvMzEzODQ1MDA0LWFiYzlhNDc3LWNhYTItNDZlZS05ZTdhLTUxYjcxMDk3MWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxOTU5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGMwZmUwMTU2ZDEzMzZiYzcwMWNiZGJmMDJjYTU5YzM5M2E2ZWY1OWIxNWE0NWVlNDA0ZDEzNzgyZjZjZTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnHDv7mEa0Iq4faYWjY3POTTzrBnJab66OQk9MAoiek)
> 
> > > sir i created a campaign but its not showing in my dashboard.? how should i solve this error as i can submit a campaign but its not displaying.
> 
> > 
> 
> > Check if your deployed contract address is equal to what has been saved in the client/src/abi/contract-address.json
> 
> 
> 
> yaa its the same as i uploaded on localhost
> 
> sir actually i need your help in this as i have to execute this project in urgent

Also pls check the browser console and let me know what is logged there after you create a new campaign?

**Comment by BahadorGh** [comment]
> > > > ![Screenshot 2024-03-19 031532](https://private-user-images.githubusercontent.com/116245115/313845004-abc9a477-caa2-46ee-9e7a-51b710971cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Nzg2NDUsIm5iZiI6MTcxMDg3ODM0NSwicGF0aCI6Ii8xMTYyNDUxMTUvMzEzODQ1MDA0LWFiYzlhNDc3LWNhYTItNDZlZS05ZTdhLTUxYjcxMDk3MWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxOTU5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGMwZmUwMTU2ZDEzMzZiYzcwMWNiZGJmMDJjYTU5YzM5M2E2ZWY1OWIxNWE0NWVlNDA0ZDEzNzgyZjZjZTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnHDv7mEa0Iq4faYWjY3POTTzrBnJab66OQk9MAoiek)
> 
> > > > sir i created a campaign but its not showing in my dashboard.? how should i solve this error as i can submit a campaign but its not displaying.
> 
> > > 
> 
> > > 
> 
> > > Check if your deployed contract address is equal to what has been saved in the client/src/abi/contract-address.json
> 
> > 
> 
> > yaa its the same as i uploaded on localhost sir actually i need your help in this as i have to execute this project in urgent
> 
> 
> 
> should i change it to sepolia contract address??

You can, but it's not necessary

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 014401](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/4d438c9b-85d0-4040-a423-1c82fc272b8f)
![Screenshot 2024-03-20 014346](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/06c86d9c-8269-44e2-8a79-0c92d1c99afc)
its showing this when i create a campaign but its not displaying on dashboard what should i do?

**Comment by BahadorGh** [comment]
> ![Screenshot 2024-03-20 014401](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/4d438c9b-85d0-4040-a423-1c82fc272b8f)
> 
> ![Screenshot 2024-03-20 014346](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/06c86d9c-8269-44e2-8a79-0c92d1c99afc)
> 
> its showing this when i create a campaign but its not displaying on dashboard what should i do?

What are your inputs for campaign creation?

**Comment by thunder1911** [comment]
> > ![Screenshot 2024-03-20 014401](https://private-user-images.githubusercontent.com/116245115/314216247-4d438c9b-85d0-4040-a423-1c82fc272b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODA0NzAsIm5iZiI6MTcxMDg4MDE3MCwicGF0aCI6Ii8xMTYyNDUxMTUvMzE0MjE2MjQ3LTRkNDM4YzliLTg1ZDAtNDA0MC1hNDIzLTFjODJmYzI3MmI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMDI5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjMxYTk2Nzk1YjZkODk1NTE0NjRhOTU0MTdiYzgxM2M2ZTBjNzVhZWE3MWE0MTZmMWFiOTgzNDVmMWI1MjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ojw6AqAUpcLlV910N0oBDHP-izDSmYvIHNLQMKN2Zb0)
> > ![Screenshot 2024-03-20 014346](https://private-user-images.githubusercontent.com/116245115/314216265-06c86d9c-8269-44e2-8a79-0c92d1c99afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODA0NzAsIm5iZiI6MTcxMDg4MDE3MCwicGF0aCI6Ii8xMTYyNDUxMTUvMzE0MjE2MjY1LTA2Yzg2ZDljLTgyNjktNDRlMi04YTc5LTBjOTJkMWM5OWFmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMDI5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzJjMWFmNzk1ZjEzMDY5OGU5MDkzMjkzOTkwMzRlZWMyNTc1MWFjMTdkM2YwOTRhZWVhYjZkMzQwZGMzYzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y0l6k_F3fKnbv8H7HBHXJU3ZxRdPW0mqA-skVChIiJ0)
> > its showing this when i create a campaign but its not displaying on dashboard what should i do?
> 
> What are your inputs for campaign creation?

name, title, story ,goal, date ,image address, and in console its also showing failed to autoconnect with the wallet as u can see above

**Comment by BahadorGh** [comment]
> > > ![Screenshot 2024-03-20 014401](https://private-user-images.githubusercontent.com/116245115/314216247-4d438c9b-85d0-4040-a423-1c82fc272b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODA0NzAsIm5iZiI6MTcxMDg4MDE3MCwicGF0aCI6Ii8xMTYyNDUxMTUvMzE0MjE2MjQ3LTRkNDM4YzliLTg1ZDAtNDA0MC1hNDIzLTFjODJmYzI3MmI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMDI5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjMxYTk2Nzk1YjZkODk1NTE0NjRhOTU0MTdiYzgxM2M2ZTBjNzVhZWE3MWE0MTZmMWFiOTgzNDVmMWI1MjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ojw6AqAUpcLlV910N0oBDHP-izDSmYvIHNLQMKN2Zb0)
> 
> > > ![Screenshot 2024-03-20 014346](https://private-user-images.githubusercontent.com/116245115/314216265-06c86d9c-8269-44e2-8a79-0c92d1c99afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODA0NzAsIm5iZiI6MTcxMDg4MDE3MCwicGF0aCI6Ii8xMTYyNDUxMTUvMzE0MjE2MjY1LTA2Yzg2ZDljLTgyNjktNDRlMi04YTc5LTBjOTJkMWM5OWFmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMDI5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzJjMWFmNzk1ZjEzMDY5OGU5MDkzMjkzOTkwMzRlZWMyNTc1MWFjMTdkM2YwOTRhZWVhYjZkMzQwZGMzYzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y0l6k_F3fKnbv8H7HBHXJU3ZxRdPW0mqA-skVChIiJ0)
> 
> > > its showing this when i create a campaign but its not displaying on dashboard what should i do?
> 
> > 
> 
> > What are your inputs for campaign creation?
> 
> 
> 
> name, title, story ,goal, date ,image address, and in console its also showing failed to autoconnect with the wallet as u can see above

Can you give me a sample campaign data you enter?

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 020609](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/89859cb7-8959-4655-8f7d-633746779fce)
![Screenshot 2024-03-20 020600](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/ed31191d-d0b6-4e84-849e-f5e48b9cb0cf)

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 020647](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/45052eeb-0927-452a-9e58-0dcc528e96af)

**Comment by BahadorGh** [comment]
Did you updated the index.js activeChain to localhost?

**Comment by thunder1911** [comment]
> Did you updated the index.js activeChain to localhost?

yes i did

**Comment by thunder1911** [comment]
index.js or main.jsx?

**Comment by BahadorGh** [comment]
Yes, main.js
It seems you are connecting to wrong network.

**Comment by thunder1911** [comment]
<ThirdwebProvider 
    desiredChainId={ChainId.Localhost}
    activeChain={ChainId.Localhost}
  > 
i did this

**Comment by thunder1911** [comment]
idk but metamask isnt showing sepolia ig
i also added my thirdweb client id

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 021903](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/caaf1346-2417-4b5d-b0e5-639f6addce45)

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 021951](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/d7d74063-c4ff-49f2-b21c-c5a43bf21cc0)
there is an option of local host here too should i try that but its showing different chainid

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 022432](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/113fbfc0-a376-48b0-bc4a-aa5ba280ee9f)
its showing this when i try to connect with local host chain id
can u please help as its my university project

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 023702](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/c35af26f-3446-467d-972c-0a25e07b7b28)

**Comment by BahadorGh** [comment]
It should be better you try it on sepolia chain

**Comment by thunder1911** [comment]
> It should be better you try it on sepolia chain

im doing it on sepolia chain

**Comment by thunder1911** [comment]
![Screenshot 2024-03-20 122342](https://github.com/BahadorGh/Donation-Dapp/assets/116245115/85360cfa-55fa-4fa8-b268-26ec6c705610)

**Comment by thunder1911** [comment]
is there any problem in infura project id?
should i use third web rpc url?

**Comment by BahadorGh** [comment]
> is there any problem in infura project id?
> 
> should i use third web rpc url?

Did you updated the .env file in your root?

**Comment by thunder1911** [comment]
yaa i have updated the env file in the web3 folder with given ids

**Comment by thunder1911** [comment]
do we have to install any packages for infura using npm?

**Comment by thunder1911** [comment]
we have commented that verify line in deploy.js file is that the problem?

**Comment by thunder1911** [comment]
Can I use thirdweb rpc to deploy this contract?

**Comment by BahadorGh** [comment]
> do we have to install any packages for infura using npm?

No i didn't

**Comment by BahadorGh** [comment]
> we have commented that verify line in deploy.js file is that the problem?

No it has nothing to do with those lines

**Comment by BahadorGh** [comment]
> Can I use thirdweb rpc to deploy this contract?

You can use any rpc you want

**Comment by thunder1911** [comment]
> > Can I use thirdweb rpc to deploy this contract?
> 
> You can use any rpc you want

I used alchemy and it's showing same error 
It's just showing 0 sepolia during transaction I think there is a problem with the metamask wallet

**Comment by thunder1911** [comment]
> > Can I use thirdweb rpc to deploy this contract?
> 
> You can use any rpc you want

Should I deploy it using npm deploy rather than using hardhat?

**Comment by BahadorGh** [comment]
You can write a script to add a campaign and then check if you can see the campaign details you created

**Comment by thunder1911** [comment]
> You can write a script to add a campaign and then check if you can see the campaign details you created

How should I write it when display campaigns is already there

**Comment by thunder1911** [comment]
> You can write a script to add a campaign and then check if you can see the campaign details you created

Or is there any chance that my contract would work if I don't deploy it on local host

**Comment by thunder1911** [comment]
> You can write a script to add a campaign and then check if you can see the campaign details you created

Or is there any chance that my contract would work if I don't deploy it on local host
And if just deploy it using thirdweb and not hardhat will it work?

**Comment by BahadorGh** [comment]
Actually I don't know what is the reason of your problem.
If I had time I would make a remote to your system and help you on that.

**Comment by thunder1911** [comment]
> Actually I don't know what is the reason of your problem. If I had time I would make a remote to your system and help you on that.

i am open to do that when can u get time can u tell?

**Comment by thunder1911** [comment]
r u free on weekends or any other time u wish?

**Comment by BahadorGh** [comment]
@thunder1911 
Hi, If you are available rn, I can make a remote to your system and check.

**Comment by thunder1911** [comment]
> @thunder1911 
> Hi, If you are available rn, I can make a remote to your system and check.

Thank you sir but when I changed the rpc to thirdweb and deployed the contract on third web it worked successfully. Thank you for ur guidance.

**Comment by BahadorGh** [comment]
> > @thunder1911
> > Hi, If you are available rn, I can make a remote to your system and check.
> 
> Thank you sir but when I changed the rpc to thirdweb and deployed the contract on third web it worked successfully. Thank you for ur guidance.

Great to hear that. so it was an error from your rpc provider.
good luck.

**Comment by BahadorGh** [comment]
Error due to rpc provider, SOLVED!
